name: Docker build CI

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build the linux Docker image
      run: docker build ./linux-x86 -t tuwienspaceteam/sts1-cobc:latest-linux-x86

    - name: Build the full Docker image
      run: docker build ./full

