name: Docker build and push CI

on:
  push:
    tags:
      - 'v*'

jobs:
  docker-linux-x86:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Copy scripts to linux-x86 build context
        run: cp install.sh ./linux-x86/. && cp libraries.txt ./linux-x86/.

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: tuwienspaceteam/sts1-cobc
          flavor: |
            latest=auto
            suffix=-linux-x86,onlatest=true
          tags: |
            type=semver,pattern={{version}}

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./linux-x86
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  docker-full:
    needs: docker-linux-x86

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Copy scripts to full build contexts 
        run: cp install.sh ./full/. && cp libraries.txt ./full/.

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: tuwienspaceteam/sts1-cobc
          flavor: |
            latest=auto
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{version}},suffix=-full

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./full
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          repository: tuwienspaceteam/sts1-cobc
